# Generated by Django 5.0.7 on 2024-07-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codeblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('template', models.TextField(max_length=60)),
                ('solution', models.TextField(max_length=60)),
                ('Content', models.TextField(max_length=200)),
                ('is_solved', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
